import type { Theme } from './theme-types.js';

// ─── Dracula ──────────────────────────────────────────────────────────────────
// A popular dark theme inspired by Dracula Pro.
export const dracula: Theme = {
	base: {
		background: '#282a36',
		color: '#f8f8f2',
		fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
		fontSize: '14px',
		lineHeight: '1.5',
		padding: '16px',
		borderRadius: '4px',
		overflowX: 'auto',
		whiteSpace: 'pre',
	},
	comment: { color: '#6272a4', fontStyle: 'italic' },
	prolog: { color: '#6272a4' },
	doctype: { color: '#6272a4' },
	cdata: { color: '#6272a4' },
	punctuation: { color: '#f8f8f2' },
	property: { color: '#ff79c6' },
	tag: { color: '#ff79c6' },
	boolean: { color: '#bd93f9' },
	number: { color: '#bd93f9' },
	constant: { color: '#bd93f9' },
	symbol: { color: '#bd93f9' },
	selector: { color: '#50fa7b' },
	'attr-name': { color: '#50fa7b' },
	string: { color: '#f1fa8c' },
	char: { color: '#f1fa8c' },
	builtin: { color: '#50fa7b' },
	operator: { color: '#ff79c6' },
	entity: { color: '#ffffb6', cursor: 'help' },
	url: { color: '#f1fa8c' },
	variable: { color: '#f8f8f2' },
	inserted: { color: '#50fa7b' },
	keyword: { color: '#ff79c6' },
	'attr-value': { color: '#f1fa8c' },
	function: { color: '#50fa7b' },
	'class-name': { color: '#8be9fd' },
	regex: { color: '#ffb86c' },
	important: { color: '#ffb86c', fontWeight: 'bold' },
	bold: { fontWeight: 'bold' },
	italic: { fontStyle: 'italic' },
	deleted: { color: '#ff5555' },
	namespace: { opacity: 0.7 },
};

// ─── GitHub Light ─────────────────────────────────────────────────────────────
export const githubLight: Theme = {
	base: {
		background: '#f6f8fa',
		color: '#24292e',
		fontFamily: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace',
		fontSize: '13px',
		lineHeight: '1.6',
		padding: '16px',
		borderRadius: '6px',
		border: '1px solid #e1e4e8',
		overflowX: 'auto',
		whiteSpace: 'pre',
	},
	comment: { color: '#6a737d', fontStyle: 'italic' },
	prolog: { color: '#6a737d' },
	doctype: { color: '#6a737d' },
	cdata: { color: '#6a737d' },
	punctuation: { color: '#24292e' },
	property: { color: '#005cc5' },
	tag: { color: '#22863a' },
	boolean: { color: '#005cc5' },
	number: { color: '#005cc5' },
	constant: { color: '#005cc5' },
	symbol: { color: '#005cc5' },
	selector: { color: '#22863a' },
	'attr-name': { color: '#6f42c1' },
	string: { color: '#032f62' },
	char: { color: '#032f62' },
	builtin: { color: '#005cc5' },
	operator: { color: '#d73a49' },
	entity: { color: '#e36209', cursor: 'help' },
	url: { color: '#032f62' },
	variable: { color: '#e36209' },
	keyword: { color: '#d73a49' },
	'attr-value': { color: '#032f62' },
	function: { color: '#6f42c1' },
	'class-name': { color: '#6f42c1' },
	regex: { color: '#032f62' },
	important: { color: '#e36209', fontWeight: 'bold' },
	bold: { fontWeight: 'bold' },
	italic: { fontStyle: 'italic' },
	inserted: { color: '#22863a' },
	deleted: { color: '#b31d28' },
	namespace: { opacity: 0.7 },
};

// ─── Night Owl ────────────────────────────────────────────────────────────────
// Dark theme by Sarah Drasner.
export const nightOwl: Theme = {
	base: {
		background: '#011627',
		color: '#d6deeb',
		fontFamily: '"Fira Code", Consolas, Monaco, monospace',
		fontSize: '14px',
		lineHeight: '1.5',
		padding: '16px',
		borderRadius: '4px',
		overflowX: 'auto',
		whiteSpace: 'pre',
	},
	comment: { color: '#637777', fontStyle: 'italic' },
	prolog: { color: '#637777' },
	doctype: { color: '#637777' },
	cdata: { color: '#637777' },
	punctuation: { color: '#c792ea' },
	property: { color: '#80cbc4' },
	tag: { color: '#7fdbca' },
	boolean: { color: '#ff5874' },
	number: { color: '#f78c6c' },
	constant: { color: '#82aaff' },
	symbol: { color: '#82aaff' },
	selector: { color: '#c792ea' },
	'attr-name': { color: '#addb67' },
	string: { color: '#ecc48d' },
	char: { color: '#ecc48d' },
	builtin: { color: '#addb67' },
	operator: { color: '#7fdbca' },
	entity: { color: '#addb67', cursor: 'help' },
	url: { color: '#ecc48d' },
	variable: { color: '#addb67' },
	keyword: { color: '#c792ea', fontStyle: 'italic' },
	'attr-value': { color: '#ecc48d' },
	function: { color: '#82aaff' },
	'class-name': { color: '#ffcb8b' },
	regex: { color: '#5ca7e4' },
	important: { color: '#c792ea', fontWeight: 'bold' },
	bold: { fontWeight: 'bold' },
	italic: { fontStyle: 'italic' },
	inserted: { color: '#addb67' },
	deleted: { color: '#ef5350' },
	namespace: { opacity: 0.7 },
};

// ─── VS Dark ──────────────────────────────────────────────────────────────────
export const vsDark: Theme = {
	base: {
		background: '#1e1e1e',
		color: '#d4d4d4',
		fontFamily: '"Cascadia Code", Consolas, "Courier New", monospace',
		fontSize: '14px',
		lineHeight: '1.5',
		padding: '16px',
		borderRadius: '4px',
		overflowX: 'auto',
		whiteSpace: 'pre',
	},
	comment: { color: '#6a9955', fontStyle: 'italic' },
	prolog: { color: '#6a9955' },
	doctype: { color: '#6a9955' },
	cdata: { color: '#6a9955' },
	punctuation: { color: '#d4d4d4' },
	property: { color: '#9cdcfe' },
	tag: { color: '#4ec9b0' },
	boolean: { color: '#569cd6' },
	number: { color: '#b5cea8' },
	constant: { color: '#9cdcfe' },
	symbol: { color: '#9cdcfe' },
	selector: { color: '#d7ba7d' },
	'attr-name': { color: '#9cdcfe' },
	string: { color: '#ce9178' },
	char: { color: '#ce9178' },
	builtin: { color: '#4ec9b0' },
	operator: { color: '#d4d4d4' },
	entity: { color: '#9cdcfe', cursor: 'help' },
	url: { color: '#ce9178' },
	variable: { color: '#9cdcfe' },
	keyword: { color: '#569cd6' },
	'attr-value': { color: '#ce9178' },
	function: { color: '#dcdcaa' },
	'class-name': { color: '#4ec9b0' },
	regex: { color: '#d16969' },
	important: { color: '#569cd6', fontWeight: 'bold' },
	bold: { fontWeight: 'bold' },
	italic: { fontStyle: 'italic' },
	inserted: { color: '#b5cea8' },
	deleted: { color: '#f44747' },
	namespace: { opacity: 0.7 },
};

/** All bundled themes — pass one to the `theme` prop of `<CodeBlock>`. */
export const themes = { dracula, githubLight, nightOwl, vsDark };
